export const apiKey = 'e7e6938f7b6d4682a55135441240412';

export const weatherImages = {
    'Partly cloudy': require('../assets/images/partlycloudy.png'), 
    'Moderate rain' : require('../assets/images/moderaterain.png'),
    'Moderate snow' : require('../assets/images/snow.png'),
    'Mist' : require('../assets/images/mist.png'),
    'Freezing fog' : require('../assets/images/mist.png'),
    'Fog' : require('../assets/images/mist.png'),
    'Light snow showers' : require('../assets/images/snow.png'),
    'Patchy moderate snow' : require('../assets/images/snow.png'),
    'Patchy light snow' : require('../assets/images/snow.png'),
    'Moderate or heavy snow showers' : require('../assets/images/snow.png'),
    'Moderate or heavy freezing rain' : require('../assets/images/snow.png'),
    'Light snow' : require('../assets/images/snow.png'),
    'Light sleet' : require('../assets/images/snow.png'),
    'Blowing snow' : require('../assets/images/snow.png'),
    'Blizzard' : require('../assets/images/snow.png'),
    'Light freezing rain' : require('../assets/images/snow.png'),
    'Light drizzle' : require('../assets/images/snow.png'),
    'Moderate or heavy sleet' : require('../assets/images/snow.png'),
    'Heavy snow' : require('../assets/images/snow.png'),
    "Partly Cloudy ": require('../assets/images/partlycloudy.png'), 
    'Patchy rain nearby': require('../assets/images/moderaterain.png'), 
    'Patchy rain possible': require('../assets/images/moderaterain.png'), 
    'Sunny': require('../assets/images/sun.png'), 
    'Clear': require('../assets/images/sun.png'),
    "Clear ": require('../assets/images/sun.png'),
    'Overcast ': require('../assets/images/cloud.png'),
    'Cloudy ': require('../assets/images/cloud.png'),
    'Cloudy': require('../assets/images/cloud.png'),
    'Light rain': require('../assets/images/moderaterain.png'),
    'Moderate rain at times': require('../assets/images/moderaterain.png'), 
    'Heavy rain': require('../assets/images/heavyrain.png'),
    'Heavy rain at times': require('../assets/images/heavyrain.png'),
    'Moderate or heavy freezing rain': require('../assets/images/heavyrain.png'), 
    'Moderate or heavy rain shower': require('../assets/images/heavyrain.png'), 
    'Moderate or heavy rain with thunder': require('../assets/images/heavyrain.png'), 
    'other': require('../assets/images/snow.png')
}

